from __future__ import annotations

from datetime import date, datetime, timedelta
import hashlib
import traceback
from typing import Any

from src.analytics.validation import resolve_validation_policy
from src.jobs.research_lifecycle import _run_strategy_lifecycle
from src.jobs.research_support import (
    DEFAULT_AGENT_TASK_TYPES,
    _build_eval_metrics,
    _build_strategy_spec,
    _extract_primary_validation_metrics,
    _strategy_status_for_rating,
)
from src.types import FundamentalSnapshot, StrategyEvaluation, StrategySpec, StrategyVersionSpec


def run_research_impl(
    limit: int | None = None,
    *,
    load_yaml_config_fn,
    load_runtime_secrets_fn,
    NeonRepository_cls,
    DiscordNotifier_cls,
    R2Storage_cls,
    compute_fundamental_rating_fn,
    run_walk_forward_validation_fn,
    parse_deep_research_file_if_configured_fn,
    build_deep_research_snapshot_fn,
) -> str:
    cfg = load_yaml_config_fn()
    secrets = load_runtime_secrets_fn()
    repo = NeonRepository_cls(secrets.database_url)
    notifier = DiscordNotifier_cls(getattr(secrets, "discord_webhook_url", None))
    r2 = R2Storage_cls(
        endpoint_url=getattr(secrets, "r2_endpoint", None),
        access_key_id=getattr(secrets, "r2_access_key_id", None),
        secret_access_key=getattr(secrets, "r2_secret_access_key", None),
        bucket_evidence=getattr(secrets, "r2_bucket_evidence", None),
        bucket_data=getattr(secrets, "r2_bucket_data", None),
    )
    run_id = repo.create_run("research", str(cfg.get("version", "1.1")), metadata={"pipeline": "strategy_factory"})
    try:
        sf_cfg = cfg.get("strategy_factory", {})
        max_parallel = int(sf_cfg.get("max_parallel_tasks", 5))
        candidate_limit = int(limit if limit is not None else sf_cfg.get("candidate_limit", 20))
        agent_task_types = sf_cfg.get("agent_roles", DEFAULT_AGENT_TASK_TYPES)
        if not isinstance(agent_task_types, list) or not agent_task_types:
            agent_task_types = list(DEFAULT_AGENT_TASK_TYPES)
        overlay_cfg = sf_cfg.get("fundamental_overlay", {})
        if not isinstance(overlay_cfg, dict):
            overlay_cfg = {}
        validation_policy = resolve_validation_policy(cfg)
        candidates = repo.fetch_latest_weekly_candidates(limit=candidate_limit)
        processed = 0
        today = date.today()
        validation_lookback_days = int(validation_policy.get("lookback_days", 365))
        for row in candidates:
            processed += 1
            security_id = str(row.get("security_id"))
            market = str(row.get("market", "JP"))
            asset_scope = "JP_EQ" if market == "JP" else "US_EQ"
            rating = compute_fundamental_rating_fn(
                combined_score=float(row.get("combined_score") or 0.0),
                confidence=str(row.get("confidence") or "Low"),
                missing_ratio=float(row.get("missing_ratio") or 1.0),
                has_major_contradiction=bool(row.get("has_major_contradiction") or False),
                primary_source_count=int(row.get("primary_source_count") or 0),
            )
            base_status = _strategy_status_for_rating(rating, overlay_cfg)
            if bool(validation_policy.get("enabled", True)):
                lookback_days = int(validation_policy.get("lookback_days", 900))
                price_history = repo.fetch_price_history_for_security(security_id=security_id, start_date=today - timedelta(days=lookback_days), end_date=today)
                validation_result = run_walk_forward_validation_fn(prices=price_history, security_id=security_id, market=market, config=cfg, policy=validation_policy)
                eval_metrics: dict[str, Any] = _extract_primary_validation_metrics(validation_result)
            else:
                validation_result = None
                eval_metrics = _build_eval_metrics(row)
                eval_metrics["validation_passed"] = True
                eval_metrics["validation_fail_reasons"] = []
            candidate_status = str(overlay_cfg.get("screening_pass_status", "candidate"))
            blocked_status = str(overlay_cfg.get("screening_block_status", "draft"))
            strategy_status = base_status if not (base_status == candidate_status and not bool(eval_metrics.get("validation_passed", False))) else blocked_status
            strategy_name = f"sf-{security_id.lower().replace(':', '-')}"
            strategy_id = repo.upsert_strategy(StrategySpec(name=strategy_name, asset_scope=asset_scope, status=strategy_status, description=f"Generated by research loop for {security_id}"))
            strategy_version_id = repo.upsert_strategy_version(StrategyVersionSpec(strategy_name=strategy_name, version=1, spec=_build_strategy_spec(row, today), created_by="research-loop", is_active=False))
            repo.insert_strategy_evaluation(StrategyEvaluation(strategy_version_id=strategy_version_id, eval_type="robust_backtest" if bool(validation_policy.get("enabled", True)) else "quick_backtest", period_start=today - timedelta(days=validation_lookback_days), period_end=today, metrics=eval_metrics, artifacts={"strategy_id": strategy_id, "run_id": run_id, "validation": validation_result}))
            repo.upsert_fundamental_snapshot(FundamentalSnapshot(security_id=security_id, as_of_date=today, source="research_loop", rating=rating, confidence=str(row.get("confidence") or "Low"), summary=f"{security_id} rating={rating} combined={float(row.get('combined_score') or 0.0):.2f}", snapshot={"drivers": ["score_combined_trend", "edge_score", "confidence_gate"], "catalysts": ["weekly_rebalance", "evidence_update"], "risks": ["drawdown_gate", "liquidity_flag"], "combined_score": float(row.get("combined_score") or 0.0), "edge_score": float(row.get("edge_score") or 0.0), "screening_status": strategy_status, "validation": validation_result or {"enabled": False}}, created_by="research-loop"))
            if strategy_status == candidate_status:
                for idx, task_type in enumerate(agent_task_types):
                    repo.enqueue_agent_task(task_type=task_type, payload={"run_id": run_id, "strategy_name": strategy_name, "strategy_version_id": strategy_version_id, "security_id": security_id, "market": market, "combined_score": float(row.get("combined_score") or 0.0), "agent_role": task_type}, priority=10 + idx)
            if processed >= max_parallel:
                break
        deep_input = parse_deep_research_file_if_configured_fn()
        deep_saved = 0
        if deep_input:
            retrieved_at = datetime.now()
            report_sha = hashlib.sha256(deep_input.report_text.encode("utf-8")).hexdigest()
            security_slug = deep_input.security_id.replace(":", "_").replace("/", "_")
            report_key = f"research/deep_research/{today.isoformat()}/{security_slug}/{report_sha}.txt"
            stored_in_r2 = r2.available()
            if stored_in_r2:
                r2.put_text(report_key, deep_input.report_text, evidence=True)
            report_source_url = f"file://{deep_input.report_path}" if getattr(deep_input, "report_path", None) else f"deep_research://{deep_input.security_id}/{today.isoformat()}"
            doc_version_id = repo.upsert_document_with_version(external_doc_id=f"{deep_input.security_id}:{report_sha}", source_system=str(getattr(deep_input, "source", "deep_research")), source_url=report_source_url, title=f"Deep Research {deep_input.security_id} {today.isoformat()}", published_at=retrieved_at, retrieved_at=retrieved_at, sha256=report_sha, mime_type="text/plain", r2_object_key=report_key, r2_text_key=report_key, page_count=1)
            deep_snapshot = build_deep_research_snapshot_fn(deep_input, api_key=secrets.openai_api_key, model=(sf_cfg.get("escalation", {}) or {}).get("heavy_model"))
            deep_snapshot_payload = dict(deep_snapshot["snapshot"])
            deep_snapshot_payload.update({"doc_version_id": doc_version_id, "r2_text_key": report_key, "sha256": report_sha})
            deep_snapshot_payload["raw_report_storage"] = "r2_evidence" if stored_in_r2 else "fundamental_snapshot_inline"
            if not stored_in_r2:
                deep_snapshot_payload["raw_report_text"] = deep_input.report_text
            try:
                repo.upsert_fundamental_snapshot(FundamentalSnapshot(security_id=deep_input.security_id, as_of_date=today, source=deep_snapshot["source"], rating=str(deep_snapshot["rating"]), confidence="High", summary=str(deep_snapshot["summary"]), snapshot=deep_snapshot_payload, created_by="deep-research-import"))
                deep_saved = 1
            except KeyError:
                deep_saved = 0
        lifecycle_summary = _run_strategy_lifecycle(repo=repo, cfg=cfg, today=today, run_id=run_id)
        kanban_counts: dict[str, int] = {}
        kanban_samples: dict[str, list[str]] = {}
        if hasattr(repo, "fetch_research_kanban_counts") and hasattr(repo, "fetch_research_kanban_samples"):
            try:
                kanban_counts = repo.fetch_research_kanban_counts()
                kanban_samples = repo.fetch_research_kanban_samples(limit_per_lane=2)
            except Exception:  # noqa: BLE001
                kanban_counts = {}
                kanban_samples = {}
        if kanban_counts:
            notifier.send_research_kanban(now=datetime.now(), counts=kanban_counts, samples=kanban_samples)
        repo.finish_run(run_id, "success", metadata={"candidate_count": len(candidates), "processed": processed, "deep_research_imported": deep_saved, "validation_policy": validation_policy, "lifecycle": lifecycle_summary, "kanban_counts": kanban_counts})
    except Exception as exc:  # noqa: BLE001
        repo.finish_run(run_id, "failed", metadata={"error": str(exc), "trace": traceback.format_exc()[-8000:]})
        raise
    return run_id


__all__ = ["run_research_impl"]
